### ISSUE TITLE
Change installer type to `phpcodesniffer-standard`

### ISSUE THREAD

**Issue by Potherca** [higidi/composer-phpcodesniffer-standards-plugin#24]
## Problem/Motivation

This composer plugin uses [`php-codesniffer-standards`](https://github.com/higidi/composer-phpcodesniffer-standards-plugin/blob/0.3.1/src/Installer.php#L19) as package type for custom codesniff packages to use. 

Some other projects that offer similar functionality (for instance [SimplyAdmire/ComposerPlugins](https://github.com/SimplyAdmire/ComposerPlugins) and [DealerDirect/phpcodesniffer-composer-installer](https://github.com/DealerDirect/phpcodesniffer-composer-installer/) use `phpcodesniffer-standard` (without the hyphen `-` between `php` and `codesniffer`.

There are also [a lot of packages](https://github.com/search?p=2&q=filename%3Acomposer.json+type+phpcodesniffer+standard&type=Code&utf8=%E2%9C%93) that adhere to this type.

## Proposed changes

It could be beneficial for the adaptation rate of all of such projects to all use the same type.

I would suggest changing the type to `phpcodesniffer-standard` before the first stable release.

**Comment by higidi** [comment]
Good point! Thx for sharing & contributing your ideas.

- [ ] I will add `phpcodesniffer-standard` as supported package type to the next development release (and first stable release).
- [ ] Think about dropping support of the current type `php-codesniffer-standards``
- [ ] Think about renaming the whole package to fit the new composer plugin type.

## For your information:
I will move the project to my own gitlab server, the URL will be https://git.higidi.com/higidi/composer-phpcodesniffer-standards-plugin

**Comment by higidi** [comment]
## Moved
see https://git.higidi.com/higidi/composer-phpcodesniffer-standards-plugin/issues/24
